### PR TITLE
fix: update deps for fix bundle compilation

### PR DESCRIPTION
**Pull request by Delagen**
#272

### CODE REVIEW

**Comment by Delagen** [comment]
@urish Try this to resolve 6.0.0 release issue

**Comment by urish** [comment]
Thanks, have you tested this?

Also, husky 6 had [some breaking changes](https://github.com/typicode/husky/releases/tag/v6.0.0), so if you upgrade it, please update the configuration accordingly

**Comment by Delagen** [comment]
Thanks. Updated MR

**Comment by urish** [comment]
Thanks for the update. Have you tested that this actually fixes the issue in #272?

**Comment by Delagen** [comment]
added "postinstall": "husky install" to support yarn.
When dist compiled, section scripts removed, so it's safe.

**Comment by urish** [comment]
I'm not sure I explained myself correctly - do we have any evidence that this change solves the issue in #272?

specifically, this:

> Error: export 'MomentModule' (imported as 'MomentModule') was not found in 'ngx-moment' (module has no exports)

**Comment by Delagen** [comment]
Error cause that bundle in es2020 in npm package consist only from root wrapper and does not contain any more code. Seems it was error in early version of 13 compiler

**Comment by urish** [comment]
Got it, thanks for explaining!

One more thing: I see the commit includes both "packages-lock.json" and "yarn.lock". Let's keep remove one of them (I don't have a strong opinion which), otherwise it's easy to get them out of sync.

**Comment by Delagen** [comment]
NPM 8 keep it sync, I think better to have NPM instead of yarn, I have seen few projects that need yarn really.

**Comment by urish** [comment]
So can you please remove yarn.lock? Not everyone has npm 8 yet

**Comment by Delagen** [comment]
Done

**Comment by urish** [comment]
released as 6.0.1

**Comment by urish** [comment]
Thanks again for looking into this

**Pull request merged**
