### PR TITLE
provide a format function as an pipe argument to customise the format

### PR DESCRIPTION
**Pull request by chaoyangnz**
Hi, I found the default format cannot fit our need. I am keen to add a feature to customise the format. I hope you can give me some feedback.

### CODE REVIEW

**Comment by urish** [comment]
Thanks! Can you also document this new parameter in the README?

**Comment by chaoyangnz** [comment]
@urish README updated

**Comment by urish** [comment]
Thanks!

**Comment by urish** [comment]
Released as 3.5.0

**Pull request merged**
