### PR TITLE
fix: moment import reworked from wildcard to default

### LINKED ISSUE #245: momentConstructor$a is not a function
Hi, I am getting the following error if I use an ngx-moment pipe. Does anybody know how to fix this, I am searching for days. 

```
ERROR TypeError: momentConstructor$a is not a function
at TimeAgoPipe.createTimer (modules.js?hash=c8c18acd318de84d628fd2f193bd914f3054af15:140401)
at TimeAgoPipe.transform (modules.js?hash=c8c18acd318de84d628fd2f193bd914f3054af15:140390)
```

**Environment:**

Please answer the following questions:

* Angular version: 9.1.12
* TypeScript version: 3.7.5
* `moment` version: ^2.24.0
* Are you using `moment-timezone`: no
* Are you using the angular-cli: no
* Using Rollup/Webpack/System.js/Ionic/similar: angular-meteor

### PR DESCRIPTION
**Pull request by Delagen**
Seem also resolve #245

### CODE REVIEW

**Comment by Delagen** [comment]
@urish Please check it

**Comment by urish** [comment]
Thanks Sergey, would you like if I added you as a maintainer for the package? (access to the repo, npm)

As I mentioned in #272 I don't have the bandwidth to maintain it and keep it up to date

**Comment by Delagen** [comment]
@urish Seem I don't know how to publish to NPM. If you describe it process, I can take a part)

**Comment by urish** [comment]
I do publish it in manual mode, though for other packages I use [np](https://www.npmjs.com/package/np) to automated publishing.

What's your NPM user name?

**Comment by Delagen** [comment]
The same, delagen

**Comment by Delagen** [comment]
@urish Any news? This is a blocker for me now.

**Comment by urish** [comment]
> How changelog is generated

Manually.

Do you have the bandwidth to maintain this package moving forward?

**Comment by Delagen** [comment]
> > How changelog is generated
> 
> Manually.
> 
> Do you have the bandwidth to maintain this package moving forward?

I can take some part time to maintain, but not sure on permanent basis. Also work full time )

**Comment by urish** [comment]
Yes, I understand. Well, that's probably better than the current situation. I've invited you to github / npm, welcome on board!

**Pull request merged**
